version: '3.4'

services:
    admin-nginx-app:
      stdin_open : true
      build:
        context:  .
        dockerfile: Dockerfile
      
      expose:
        - 5174
      ports:
        - "5174:80"
      environment:
        - CHOKIDAR_USEPOLLING=true
      
      volumes:
        - .:/app  
